//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPI_SUPPORT_WIP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALL_SETTINGS_THE_CUSTOMERS
    {
        public string MODEL { get; set; }
        public string PATH_LOG { get; set; }
        public string OUTPUT_LOG { get; set; }
        public string STATION { get; set; }
        public Nullable<int> TIME_SLEEP { get; set; }
        public Nullable<int> LOCATION { get; set; }
        public Nullable<int> LENGTH_SERIAL { get; set; }
        public Nullable<int> INDEX { get; set; }
        public Nullable<int> TO { get; set; }
        public string PROCESS { get; set; }
        public Nullable<int> PCP_SHEET { get; set; }
        public string PC_NAME { get; set; }
        public int TABLE_ID { get; set; }
        public Nullable<int> STATION_INDEX { get; set; }
        public Nullable<int> STATION_TO { get; set; }
        public string OLD_STATION { get; set; }
        public string NOTE { get; set; }
        public Nullable<bool> IS_SPECIAL { get; set; }
    }
}
