//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPI_SUPPORT_WIP.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SOFTWAREEntities : DbContext
    {
        public SOFTWAREEntities()
            : base("name=SOFTWAREEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ALL_SETTINGS_THE_CUSTOMERS> ALL_SETTINGS_THE_CUSTOMERS { get; set; }
        public DbSet<USER> USERs { get; set; }
    }
}
