//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPI_SUPPORT_WIP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCANNING_LOGS
    {
        public string BASE_NO { get; set; }
        public int BOARD_COUNT { get; set; }
        public string BOARD_NO { get; set; }
        public int BOARD_STATE { get; set; }
        public string CASE_NO { get; set; }
        public string CLIENT_NAME { get; set; }
        public string CUSTOMER_ID { get; set; }
        public string EDI_NO { get; set; }
        public string HOST_NAME { get; set; }
        public System.Guid ID { get; set; }
        public bool IS_REVERTED { get; set; }
        public string LINE_ID { get; set; }
        public string LOT_NO { get; set; }
        public System.Guid ORDER_ID { get; set; }
        public string ORDER_NO { get; set; }
        public string PACKING_NO { get; set; }
        public string PACKING_ORDER_NO { get; set; }
        public string PART_ID { get; set; }
        public string PART_NO { get; set; }
        public string PLANT { get; set; }
        public int PROCEDURE_INDEX { get; set; }
        public string PRODUCT_ID { get; set; }
        public int SECTION { get; set; }
        public string STATION_NAME { get; set; }
        public string STATION_NO { get; set; }
        public int STATION_TYPE { get; set; }
        public System.DateTime UPDATE_TIME { get; set; }
        public string UPDATER_NAME { get; set; }
        public string UPN_ID { get; set; }
    }
}
