//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIVN_PACKING.Entitis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Models
    {
        public int ID { get; set; }
        public string MODEL { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
    }
}
