//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIVN_PACKING.Entitis
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Produce
    {
        [Browsable(false)]
        public int ID { get; set; }
        public string USER_NAME { get; set; }
        public string MODEL { get; set; }
        public string NAME_WO { get; set; }
        public string WO { get; set; }
        public string BOXID { get; set; }
        public string SERIAL { get; set; }
        public string SERIAL_START { get; set; }
        public string SERIAL_END { get; set; }
        public string AMOUNT { get; set; }
       
        public Nullable<System.DateTime> DATECREATE { get; set; }
      
      
    }
}
