//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIVN_PACKING.Entitis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<bool> IS_ADMIN { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<bool> ENABLE { get; set; }
    }
}
