//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIVN_PACKING.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BIVN_PACKING.ServiceReference1.BCLBFLMEntity))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BCLBFLMEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BCLBFLMEntity : BIVN_PACKING.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BC_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BC_TYPEField;
        
        private System.Nullable<System.DateTime> REQ_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TN_NOField;
        
        private System.Nullable<int> TN_LINEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PART_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MPN_NOField;
        
        private System.Nullable<decimal> REQ_QTYField;
        
        private System.Nullable<decimal> OS_QTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_NOField;
        
        private System.Nullable<int> PO_LINEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VEN_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VEN_BRCDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DATE_CODEField;
        
        private System.Nullable<int> PRN_COUNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BC_SITEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WH_CODEField;
        
        private System.Nullable<System.DateTime> ISS_DATEField;
        
        private System.Nullable<System.DateTime> RQC_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPD_USERField;
        
        private System.Nullable<System.DateTime> UPD_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WH_LOCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VEN_LTNOField;
        
        private System.Nullable<System.DateTime> MAKE_DATEField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BC_NO {
            get {
                return this.BC_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.BC_NOField, value) != true)) {
                    this.BC_NOField = value;
                    this.RaisePropertyChanged("BC_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BC_TYPE {
            get {
                return this.BC_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.BC_TYPEField, value) != true)) {
                    this.BC_TYPEField = value;
                    this.RaisePropertyChanged("BC_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> REQ_DATE {
            get {
                return this.REQ_DATEField;
            }
            set {
                if ((this.REQ_DATEField.Equals(value) != true)) {
                    this.REQ_DATEField = value;
                    this.RaisePropertyChanged("REQ_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TN_NO {
            get {
                return this.TN_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.TN_NOField, value) != true)) {
                    this.TN_NOField = value;
                    this.RaisePropertyChanged("TN_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> TN_LINE {
            get {
                return this.TN_LINEField;
            }
            set {
                if ((this.TN_LINEField.Equals(value) != true)) {
                    this.TN_LINEField = value;
                    this.RaisePropertyChanged("TN_LINE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PART_NO {
            get {
                return this.PART_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PART_NOField, value) != true)) {
                    this.PART_NOField = value;
                    this.RaisePropertyChanged("PART_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MPN_NO {
            get {
                return this.MPN_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.MPN_NOField, value) != true)) {
                    this.MPN_NOField = value;
                    this.RaisePropertyChanged("MPN_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<decimal> REQ_QTY {
            get {
                return this.REQ_QTYField;
            }
            set {
                if ((this.REQ_QTYField.Equals(value) != true)) {
                    this.REQ_QTYField = value;
                    this.RaisePropertyChanged("REQ_QTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<decimal> OS_QTY {
            get {
                return this.OS_QTYField;
            }
            set {
                if ((this.OS_QTYField.Equals(value) != true)) {
                    this.OS_QTYField = value;
                    this.RaisePropertyChanged("OS_QTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string PO_NO {
            get {
                return this.PO_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_NOField, value) != true)) {
                    this.PO_NOField = value;
                    this.RaisePropertyChanged("PO_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<int> PO_LINE {
            get {
                return this.PO_LINEField;
            }
            set {
                if ((this.PO_LINEField.Equals(value) != true)) {
                    this.PO_LINEField = value;
                    this.RaisePropertyChanged("PO_LINE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string VEN_CODE {
            get {
                return this.VEN_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.VEN_CODEField, value) != true)) {
                    this.VEN_CODEField = value;
                    this.RaisePropertyChanged("VEN_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string VEN_BRCD {
            get {
                return this.VEN_BRCDField;
            }
            set {
                if ((object.ReferenceEquals(this.VEN_BRCDField, value) != true)) {
                    this.VEN_BRCDField = value;
                    this.RaisePropertyChanged("VEN_BRCD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string DATE_CODE {
            get {
                return this.DATE_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.DATE_CODEField, value) != true)) {
                    this.DATE_CODEField = value;
                    this.RaisePropertyChanged("DATE_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.Nullable<int> PRN_COUNT {
            get {
                return this.PRN_COUNTField;
            }
            set {
                if ((this.PRN_COUNTField.Equals(value) != true)) {
                    this.PRN_COUNTField = value;
                    this.RaisePropertyChanged("PRN_COUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string BC_SITE {
            get {
                return this.BC_SITEField;
            }
            set {
                if ((object.ReferenceEquals(this.BC_SITEField, value) != true)) {
                    this.BC_SITEField = value;
                    this.RaisePropertyChanged("BC_SITE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string WH_CODE {
            get {
                return this.WH_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.WH_CODEField, value) != true)) {
                    this.WH_CODEField = value;
                    this.RaisePropertyChanged("WH_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.Nullable<System.DateTime> ISS_DATE {
            get {
                return this.ISS_DATEField;
            }
            set {
                if ((this.ISS_DATEField.Equals(value) != true)) {
                    this.ISS_DATEField = value;
                    this.RaisePropertyChanged("ISS_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public System.Nullable<System.DateTime> RQC_DATE {
            get {
                return this.RQC_DATEField;
            }
            set {
                if ((this.RQC_DATEField.Equals(value) != true)) {
                    this.RQC_DATEField = value;
                    this.RaisePropertyChanged("RQC_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string UPD_USER {
            get {
                return this.UPD_USERField;
            }
            set {
                if ((object.ReferenceEquals(this.UPD_USERField, value) != true)) {
                    this.UPD_USERField = value;
                    this.RaisePropertyChanged("UPD_USER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public System.Nullable<System.DateTime> UPD_DATE {
            get {
                return this.UPD_DATEField;
            }
            set {
                if ((this.UPD_DATEField.Equals(value) != true)) {
                    this.UPD_DATEField = value;
                    this.RaisePropertyChanged("UPD_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string WH_LOC {
            get {
                return this.WH_LOCField;
            }
            set {
                if ((object.ReferenceEquals(this.WH_LOCField, value) != true)) {
                    this.WH_LOCField = value;
                    this.RaisePropertyChanged("WH_LOC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string VEN_LTNO {
            get {
                return this.VEN_LTNOField;
            }
            set {
                if ((object.ReferenceEquals(this.VEN_LTNOField, value) != true)) {
                    this.VEN_LTNOField = value;
                    this.RaisePropertyChanged("VEN_LTNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public System.Nullable<System.DateTime> MAKE_DATE {
            get {
                return this.MAKE_DATEField;
            }
            set {
                if ((this.MAKE_DATEField.Equals(value) != true)) {
                    this.MAKE_DATEField = value;
                    this.RaisePropertyChanged("MAKE_DATE");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.USAPWebServiceSoap")]
    public interface USAPWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name BC_NO from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByBcNo", ReplyAction="*")]
        BIVN_PACKING.ServiceReference1.GetByBcNoResponse GetByBcNo(BIVN_PACKING.ServiceReference1.GetByBcNoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByBcNo", ReplyAction="*")]
        System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.GetByBcNoResponse> GetByBcNoAsync(BIVN_PACKING.ServiceReference1.GetByBcNoRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetActualProduct", ReplyAction="*")]
        BIVN_PACKING.ServiceReference1.GetActualProductResponse GetActualProduct(BIVN_PACKING.ServiceReference1.GetActualProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetActualProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.GetActualProductResponse> GetActualProductAsync(BIVN_PACKING.ServiceReference1.GetActualProductRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetActualProductWidthKey", ReplyAction="*")]
        BIVN_PACKING.ServiceReference1.GetActualProductWidthKeyResponse GetActualProductWidthKey(BIVN_PACKING.ServiceReference1.GetActualProductWidthKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetActualProductWidthKey", ReplyAction="*")]
        System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.GetActualProductWidthKeyResponse> GetActualProductWidthKeyAsync(BIVN_PACKING.ServiceReference1.GetActualProductWidthKeyRequest request);
        
        // CODEGEN: Generating message contract since element name issue from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByIssueSheet", ReplyAction="*")]
        BIVN_PACKING.ServiceReference1.GetByIssueSheetResponse GetByIssueSheet(BIVN_PACKING.ServiceReference1.GetByIssueSheetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByIssueSheet", ReplyAction="*")]
        System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.GetByIssueSheetResponse> GetByIssueSheetAsync(BIVN_PACKING.ServiceReference1.GetByIssueSheetRequest request);
        
        // CODEGEN: Generating message contract since element name GetListReportResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListReport", ReplyAction="*")]
        BIVN_PACKING.ServiceReference1.GetListReportResponse GetListReport(BIVN_PACKING.ServiceReference1.GetListReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListReport", ReplyAction="*")]
        System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.GetListReportResponse> GetListReportAsync(BIVN_PACKING.ServiceReference1.GetListReportRequest request);
        
        // CODEGEN: Generating message contract since element name GetDataPointsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataPoints", ReplyAction="*")]
        BIVN_PACKING.ServiceReference1.GetDataPointsResponse GetDataPoints(BIVN_PACKING.ServiceReference1.GetDataPointsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataPoints", ReplyAction="*")]
        System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.GetDataPointsResponse> GetDataPointsAsync(BIVN_PACKING.ServiceReference1.GetDataPointsRequest request);
        
        // CODEGEN: Generating message contract since element name GetDataPointConfirmsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataPointConfirms", ReplyAction="*")]
        BIVN_PACKING.ServiceReference1.GetDataPointConfirmsResponse GetDataPointConfirms(BIVN_PACKING.ServiceReference1.GetDataPointConfirmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataPointConfirms", ReplyAction="*")]
        System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.GetDataPointConfirmsResponse> GetDataPointConfirmsAsync(BIVN_PACKING.ServiceReference1.GetDataPointConfirmsRequest request);
        
        // CODEGEN: Generating message contract since element name DailyResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Daily", ReplyAction="*")]
        BIVN_PACKING.ServiceReference1.DailyResponse Daily(BIVN_PACKING.ServiceReference1.DailyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Daily", ReplyAction="*")]
        System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.DailyResponse> DailyAsync(BIVN_PACKING.ServiceReference1.DailyRequest request);
        
        // CODEGEN: Generating message contract since element name MonthlyResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Monthly", ReplyAction="*")]
        BIVN_PACKING.ServiceReference1.MonthlyResponse Monthly(BIVN_PACKING.ServiceReference1.MonthlyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Monthly", ReplyAction="*")]
        System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.MonthlyResponse> MonthlyAsync(BIVN_PACKING.ServiceReference1.MonthlyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByBcNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByBcNo", Namespace="http://tempuri.org/", Order=0)]
        public BIVN_PACKING.ServiceReference1.GetByBcNoRequestBody Body;
        
        public GetByBcNoRequest() {
        }
        
        public GetByBcNoRequest(BIVN_PACKING.ServiceReference1.GetByBcNoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByBcNoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BC_NO;
        
        public GetByBcNoRequestBody() {
        }
        
        public GetByBcNoRequestBody(string BC_NO) {
            this.BC_NO = BC_NO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByBcNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByBcNoResponse", Namespace="http://tempuri.org/", Order=0)]
        public BIVN_PACKING.ServiceReference1.GetByBcNoResponseBody Body;
        
        public GetByBcNoResponse() {
        }
        
        public GetByBcNoResponse(BIVN_PACKING.ServiceReference1.GetByBcNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByBcNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BIVN_PACKING.ServiceReference1.BCLBFLMEntity GetByBcNoResult;
        
        public GetByBcNoResponseBody() {
        }
        
        public GetByBcNoResponseBody(BIVN_PACKING.ServiceReference1.BCLBFLMEntity GetByBcNoResult) {
            this.GetByBcNoResult = GetByBcNoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActualProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActualProduct", Namespace="http://tempuri.org/", Order=0)]
        public BIVN_PACKING.ServiceReference1.GetActualProductRequestBody Body;
        
        public GetActualProductRequest() {
        }
        
        public GetActualProductRequest(BIVN_PACKING.ServiceReference1.GetActualProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetActualProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime startTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime endTime;
        
        public GetActualProductRequestBody() {
        }
        
        public GetActualProductRequestBody(string user, System.DateTime startTime, System.DateTime endTime) {
            this.user = user;
            this.startTime = startTime;
            this.endTime = endTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActualProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActualProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public BIVN_PACKING.ServiceReference1.GetActualProductResponseBody Body;
        
        public GetActualProductResponse() {
        }
        
        public GetActualProductResponse(BIVN_PACKING.ServiceReference1.GetActualProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetActualProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetActualProductResult;
        
        public GetActualProductResponseBody() {
        }
        
        public GetActualProductResponseBody(string GetActualProductResult) {
            this.GetActualProductResult = GetActualProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActualProductWidthKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActualProductWidthKey", Namespace="http://tempuri.org/", Order=0)]
        public BIVN_PACKING.ServiceReference1.GetActualProductWidthKeyRequestBody Body;
        
        public GetActualProductWidthKeyRequest() {
        }
        
        public GetActualProductWidthKeyRequest(BIVN_PACKING.ServiceReference1.GetActualProductWidthKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetActualProductWidthKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime startTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime endTime;
        
        public GetActualProductWidthKeyRequestBody() {
        }
        
        public GetActualProductWidthKeyRequestBody(string user, string key, System.DateTime startTime, System.DateTime endTime) {
            this.user = user;
            this.key = key;
            this.startTime = startTime;
            this.endTime = endTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActualProductWidthKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActualProductWidthKeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public BIVN_PACKING.ServiceReference1.GetActualProductWidthKeyResponseBody Body;
        
        public GetActualProductWidthKeyResponse() {
        }
        
        public GetActualProductWidthKeyResponse(BIVN_PACKING.ServiceReference1.GetActualProductWidthKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetActualProductWidthKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetActualProductWidthKeyResult;
        
        public GetActualProductWidthKeyResponseBody() {
        }
        
        public GetActualProductWidthKeyResponseBody(string GetActualProductWidthKeyResult) {
            this.GetActualProductWidthKeyResult = GetActualProductWidthKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIssueSheetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByIssueSheet", Namespace="http://tempuri.org/", Order=0)]
        public BIVN_PACKING.ServiceReference1.GetByIssueSheetRequestBody Body;
        
        public GetByIssueSheetRequest() {
        }
        
        public GetByIssueSheetRequest(BIVN_PACKING.ServiceReference1.GetByIssueSheetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIssueSheetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string issue;
        
        public GetByIssueSheetRequestBody() {
        }
        
        public GetByIssueSheetRequestBody(string issue) {
            this.issue = issue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIssueSheetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByIssueSheetResponse", Namespace="http://tempuri.org/", Order=0)]
        public BIVN_PACKING.ServiceReference1.GetByIssueSheetResponseBody Body;
        
        public GetByIssueSheetResponse() {
        }
        
        public GetByIssueSheetResponse(BIVN_PACKING.ServiceReference1.GetByIssueSheetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIssueSheetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetByIssueSheetResult;
        
        public GetByIssueSheetResponseBody() {
        }
        
        public GetByIssueSheetResponseBody(string GetByIssueSheetResult) {
            this.GetByIssueSheetResult = GetByIssueSheetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListReport", Namespace="http://tempuri.org/", Order=0)]
        public BIVN_PACKING.ServiceReference1.GetListReportRequestBody Body;
        
        public GetListReportRequest() {
        }
        
        public GetListReportRequest(BIVN_PACKING.ServiceReference1.GetListReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetListReportRequestBody {
        
        public GetListReportRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public BIVN_PACKING.ServiceReference1.GetListReportResponseBody Body;
        
        public GetListReportResponse() {
        }
        
        public GetListReportResponse(BIVN_PACKING.ServiceReference1.GetListReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetListReportResult;
        
        public GetListReportResponseBody() {
        }
        
        public GetListReportResponseBody(string GetListReportResult) {
            this.GetListReportResult = GetListReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataPointsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataPoints", Namespace="http://tempuri.org/", Order=0)]
        public BIVN_PACKING.ServiceReference1.GetDataPointsRequestBody Body;
        
        public GetDataPointsRequest() {
        }
        
        public GetDataPointsRequest(BIVN_PACKING.ServiceReference1.GetDataPointsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDataPointsRequestBody {
        
        public GetDataPointsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataPointsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataPointsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BIVN_PACKING.ServiceReference1.GetDataPointsResponseBody Body;
        
        public GetDataPointsResponse() {
        }
        
        public GetDataPointsResponse(BIVN_PACKING.ServiceReference1.GetDataPointsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataPointsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataPointsResult;
        
        public GetDataPointsResponseBody() {
        }
        
        public GetDataPointsResponseBody(string GetDataPointsResult) {
            this.GetDataPointsResult = GetDataPointsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataPointConfirmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataPointConfirms", Namespace="http://tempuri.org/", Order=0)]
        public BIVN_PACKING.ServiceReference1.GetDataPointConfirmsRequestBody Body;
        
        public GetDataPointConfirmsRequest() {
        }
        
        public GetDataPointConfirmsRequest(BIVN_PACKING.ServiceReference1.GetDataPointConfirmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDataPointConfirmsRequestBody {
        
        public GetDataPointConfirmsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataPointConfirmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataPointConfirmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BIVN_PACKING.ServiceReference1.GetDataPointConfirmsResponseBody Body;
        
        public GetDataPointConfirmsResponse() {
        }
        
        public GetDataPointConfirmsResponse(BIVN_PACKING.ServiceReference1.GetDataPointConfirmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataPointConfirmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataPointConfirmsResult;
        
        public GetDataPointConfirmsResponseBody() {
        }
        
        public GetDataPointConfirmsResponseBody(string GetDataPointConfirmsResult) {
            this.GetDataPointConfirmsResult = GetDataPointConfirmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DailyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Daily", Namespace="http://tempuri.org/", Order=0)]
        public BIVN_PACKING.ServiceReference1.DailyRequestBody Body;
        
        public DailyRequest() {
        }
        
        public DailyRequest(BIVN_PACKING.ServiceReference1.DailyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DailyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime input;
        
        public DailyRequestBody() {
        }
        
        public DailyRequestBody(System.DateTime input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DailyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DailyResponse", Namespace="http://tempuri.org/", Order=0)]
        public BIVN_PACKING.ServiceReference1.DailyResponseBody Body;
        
        public DailyResponse() {
        }
        
        public DailyResponse(BIVN_PACKING.ServiceReference1.DailyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DailyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DailyResult;
        
        public DailyResponseBody() {
        }
        
        public DailyResponseBody(string DailyResult) {
            this.DailyResult = DailyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MonthlyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Monthly", Namespace="http://tempuri.org/", Order=0)]
        public BIVN_PACKING.ServiceReference1.MonthlyRequestBody Body;
        
        public MonthlyRequest() {
        }
        
        public MonthlyRequest(BIVN_PACKING.ServiceReference1.MonthlyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MonthlyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime input;
        
        public MonthlyRequestBody() {
        }
        
        public MonthlyRequestBody(System.DateTime input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MonthlyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MonthlyResponse", Namespace="http://tempuri.org/", Order=0)]
        public BIVN_PACKING.ServiceReference1.MonthlyResponseBody Body;
        
        public MonthlyResponse() {
        }
        
        public MonthlyResponse(BIVN_PACKING.ServiceReference1.MonthlyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MonthlyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MonthlyResult;
        
        public MonthlyResponseBody() {
        }
        
        public MonthlyResponseBody(string MonthlyResult) {
            this.MonthlyResult = MonthlyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface USAPWebServiceSoapChannel : BIVN_PACKING.ServiceReference1.USAPWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class USAPWebServiceSoapClient : System.ServiceModel.ClientBase<BIVN_PACKING.ServiceReference1.USAPWebServiceSoap>, BIVN_PACKING.ServiceReference1.USAPWebServiceSoap {
        
        public USAPWebServiceSoapClient() {
        }
        
        public USAPWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public USAPWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public USAPWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public USAPWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BIVN_PACKING.ServiceReference1.GetByBcNoResponse BIVN_PACKING.ServiceReference1.USAPWebServiceSoap.GetByBcNo(BIVN_PACKING.ServiceReference1.GetByBcNoRequest request) {
            return base.Channel.GetByBcNo(request);
        }
        
        public BIVN_PACKING.ServiceReference1.BCLBFLMEntity GetByBcNo(string BC_NO) {
            BIVN_PACKING.ServiceReference1.GetByBcNoRequest inValue = new BIVN_PACKING.ServiceReference1.GetByBcNoRequest();
            inValue.Body = new BIVN_PACKING.ServiceReference1.GetByBcNoRequestBody();
            inValue.Body.BC_NO = BC_NO;
            BIVN_PACKING.ServiceReference1.GetByBcNoResponse retVal = ((BIVN_PACKING.ServiceReference1.USAPWebServiceSoap)(this)).GetByBcNo(inValue);
            return retVal.Body.GetByBcNoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.GetByBcNoResponse> BIVN_PACKING.ServiceReference1.USAPWebServiceSoap.GetByBcNoAsync(BIVN_PACKING.ServiceReference1.GetByBcNoRequest request) {
            return base.Channel.GetByBcNoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.GetByBcNoResponse> GetByBcNoAsync(string BC_NO) {
            BIVN_PACKING.ServiceReference1.GetByBcNoRequest inValue = new BIVN_PACKING.ServiceReference1.GetByBcNoRequest();
            inValue.Body = new BIVN_PACKING.ServiceReference1.GetByBcNoRequestBody();
            inValue.Body.BC_NO = BC_NO;
            return ((BIVN_PACKING.ServiceReference1.USAPWebServiceSoap)(this)).GetByBcNoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BIVN_PACKING.ServiceReference1.GetActualProductResponse BIVN_PACKING.ServiceReference1.USAPWebServiceSoap.GetActualProduct(BIVN_PACKING.ServiceReference1.GetActualProductRequest request) {
            return base.Channel.GetActualProduct(request);
        }
        
        public string GetActualProduct(string user, System.DateTime startTime, System.DateTime endTime) {
            BIVN_PACKING.ServiceReference1.GetActualProductRequest inValue = new BIVN_PACKING.ServiceReference1.GetActualProductRequest();
            inValue.Body = new BIVN_PACKING.ServiceReference1.GetActualProductRequestBody();
            inValue.Body.user = user;
            inValue.Body.startTime = startTime;
            inValue.Body.endTime = endTime;
            BIVN_PACKING.ServiceReference1.GetActualProductResponse retVal = ((BIVN_PACKING.ServiceReference1.USAPWebServiceSoap)(this)).GetActualProduct(inValue);
            return retVal.Body.GetActualProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.GetActualProductResponse> BIVN_PACKING.ServiceReference1.USAPWebServiceSoap.GetActualProductAsync(BIVN_PACKING.ServiceReference1.GetActualProductRequest request) {
            return base.Channel.GetActualProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.GetActualProductResponse> GetActualProductAsync(string user, System.DateTime startTime, System.DateTime endTime) {
            BIVN_PACKING.ServiceReference1.GetActualProductRequest inValue = new BIVN_PACKING.ServiceReference1.GetActualProductRequest();
            inValue.Body = new BIVN_PACKING.ServiceReference1.GetActualProductRequestBody();
            inValue.Body.user = user;
            inValue.Body.startTime = startTime;
            inValue.Body.endTime = endTime;
            return ((BIVN_PACKING.ServiceReference1.USAPWebServiceSoap)(this)).GetActualProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BIVN_PACKING.ServiceReference1.GetActualProductWidthKeyResponse BIVN_PACKING.ServiceReference1.USAPWebServiceSoap.GetActualProductWidthKey(BIVN_PACKING.ServiceReference1.GetActualProductWidthKeyRequest request) {
            return base.Channel.GetActualProductWidthKey(request);
        }
        
        public string GetActualProductWidthKey(string user, string key, System.DateTime startTime, System.DateTime endTime) {
            BIVN_PACKING.ServiceReference1.GetActualProductWidthKeyRequest inValue = new BIVN_PACKING.ServiceReference1.GetActualProductWidthKeyRequest();
            inValue.Body = new BIVN_PACKING.ServiceReference1.GetActualProductWidthKeyRequestBody();
            inValue.Body.user = user;
            inValue.Body.key = key;
            inValue.Body.startTime = startTime;
            inValue.Body.endTime = endTime;
            BIVN_PACKING.ServiceReference1.GetActualProductWidthKeyResponse retVal = ((BIVN_PACKING.ServiceReference1.USAPWebServiceSoap)(this)).GetActualProductWidthKey(inValue);
            return retVal.Body.GetActualProductWidthKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.GetActualProductWidthKeyResponse> BIVN_PACKING.ServiceReference1.USAPWebServiceSoap.GetActualProductWidthKeyAsync(BIVN_PACKING.ServiceReference1.GetActualProductWidthKeyRequest request) {
            return base.Channel.GetActualProductWidthKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.GetActualProductWidthKeyResponse> GetActualProductWidthKeyAsync(string user, string key, System.DateTime startTime, System.DateTime endTime) {
            BIVN_PACKING.ServiceReference1.GetActualProductWidthKeyRequest inValue = new BIVN_PACKING.ServiceReference1.GetActualProductWidthKeyRequest();
            inValue.Body = new BIVN_PACKING.ServiceReference1.GetActualProductWidthKeyRequestBody();
            inValue.Body.user = user;
            inValue.Body.key = key;
            inValue.Body.startTime = startTime;
            inValue.Body.endTime = endTime;
            return ((BIVN_PACKING.ServiceReference1.USAPWebServiceSoap)(this)).GetActualProductWidthKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BIVN_PACKING.ServiceReference1.GetByIssueSheetResponse BIVN_PACKING.ServiceReference1.USAPWebServiceSoap.GetByIssueSheet(BIVN_PACKING.ServiceReference1.GetByIssueSheetRequest request) {
            return base.Channel.GetByIssueSheet(request);
        }
        
        public string GetByIssueSheet(string issue) {
            BIVN_PACKING.ServiceReference1.GetByIssueSheetRequest inValue = new BIVN_PACKING.ServiceReference1.GetByIssueSheetRequest();
            inValue.Body = new BIVN_PACKING.ServiceReference1.GetByIssueSheetRequestBody();
            inValue.Body.issue = issue;
            BIVN_PACKING.ServiceReference1.GetByIssueSheetResponse retVal = ((BIVN_PACKING.ServiceReference1.USAPWebServiceSoap)(this)).GetByIssueSheet(inValue);
            return retVal.Body.GetByIssueSheetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.GetByIssueSheetResponse> BIVN_PACKING.ServiceReference1.USAPWebServiceSoap.GetByIssueSheetAsync(BIVN_PACKING.ServiceReference1.GetByIssueSheetRequest request) {
            return base.Channel.GetByIssueSheetAsync(request);
        }
        
        public System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.GetByIssueSheetResponse> GetByIssueSheetAsync(string issue) {
            BIVN_PACKING.ServiceReference1.GetByIssueSheetRequest inValue = new BIVN_PACKING.ServiceReference1.GetByIssueSheetRequest();
            inValue.Body = new BIVN_PACKING.ServiceReference1.GetByIssueSheetRequestBody();
            inValue.Body.issue = issue;
            return ((BIVN_PACKING.ServiceReference1.USAPWebServiceSoap)(this)).GetByIssueSheetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BIVN_PACKING.ServiceReference1.GetListReportResponse BIVN_PACKING.ServiceReference1.USAPWebServiceSoap.GetListReport(BIVN_PACKING.ServiceReference1.GetListReportRequest request) {
            return base.Channel.GetListReport(request);
        }
        
        public string GetListReport() {
            BIVN_PACKING.ServiceReference1.GetListReportRequest inValue = new BIVN_PACKING.ServiceReference1.GetListReportRequest();
            inValue.Body = new BIVN_PACKING.ServiceReference1.GetListReportRequestBody();
            BIVN_PACKING.ServiceReference1.GetListReportResponse retVal = ((BIVN_PACKING.ServiceReference1.USAPWebServiceSoap)(this)).GetListReport(inValue);
            return retVal.Body.GetListReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.GetListReportResponse> BIVN_PACKING.ServiceReference1.USAPWebServiceSoap.GetListReportAsync(BIVN_PACKING.ServiceReference1.GetListReportRequest request) {
            return base.Channel.GetListReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.GetListReportResponse> GetListReportAsync() {
            BIVN_PACKING.ServiceReference1.GetListReportRequest inValue = new BIVN_PACKING.ServiceReference1.GetListReportRequest();
            inValue.Body = new BIVN_PACKING.ServiceReference1.GetListReportRequestBody();
            return ((BIVN_PACKING.ServiceReference1.USAPWebServiceSoap)(this)).GetListReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BIVN_PACKING.ServiceReference1.GetDataPointsResponse BIVN_PACKING.ServiceReference1.USAPWebServiceSoap.GetDataPoints(BIVN_PACKING.ServiceReference1.GetDataPointsRequest request) {
            return base.Channel.GetDataPoints(request);
        }
        
        public string GetDataPoints() {
            BIVN_PACKING.ServiceReference1.GetDataPointsRequest inValue = new BIVN_PACKING.ServiceReference1.GetDataPointsRequest();
            inValue.Body = new BIVN_PACKING.ServiceReference1.GetDataPointsRequestBody();
            BIVN_PACKING.ServiceReference1.GetDataPointsResponse retVal = ((BIVN_PACKING.ServiceReference1.USAPWebServiceSoap)(this)).GetDataPoints(inValue);
            return retVal.Body.GetDataPointsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.GetDataPointsResponse> BIVN_PACKING.ServiceReference1.USAPWebServiceSoap.GetDataPointsAsync(BIVN_PACKING.ServiceReference1.GetDataPointsRequest request) {
            return base.Channel.GetDataPointsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.GetDataPointsResponse> GetDataPointsAsync() {
            BIVN_PACKING.ServiceReference1.GetDataPointsRequest inValue = new BIVN_PACKING.ServiceReference1.GetDataPointsRequest();
            inValue.Body = new BIVN_PACKING.ServiceReference1.GetDataPointsRequestBody();
            return ((BIVN_PACKING.ServiceReference1.USAPWebServiceSoap)(this)).GetDataPointsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BIVN_PACKING.ServiceReference1.GetDataPointConfirmsResponse BIVN_PACKING.ServiceReference1.USAPWebServiceSoap.GetDataPointConfirms(BIVN_PACKING.ServiceReference1.GetDataPointConfirmsRequest request) {
            return base.Channel.GetDataPointConfirms(request);
        }
        
        public string GetDataPointConfirms() {
            BIVN_PACKING.ServiceReference1.GetDataPointConfirmsRequest inValue = new BIVN_PACKING.ServiceReference1.GetDataPointConfirmsRequest();
            inValue.Body = new BIVN_PACKING.ServiceReference1.GetDataPointConfirmsRequestBody();
            BIVN_PACKING.ServiceReference1.GetDataPointConfirmsResponse retVal = ((BIVN_PACKING.ServiceReference1.USAPWebServiceSoap)(this)).GetDataPointConfirms(inValue);
            return retVal.Body.GetDataPointConfirmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.GetDataPointConfirmsResponse> BIVN_PACKING.ServiceReference1.USAPWebServiceSoap.GetDataPointConfirmsAsync(BIVN_PACKING.ServiceReference1.GetDataPointConfirmsRequest request) {
            return base.Channel.GetDataPointConfirmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.GetDataPointConfirmsResponse> GetDataPointConfirmsAsync() {
            BIVN_PACKING.ServiceReference1.GetDataPointConfirmsRequest inValue = new BIVN_PACKING.ServiceReference1.GetDataPointConfirmsRequest();
            inValue.Body = new BIVN_PACKING.ServiceReference1.GetDataPointConfirmsRequestBody();
            return ((BIVN_PACKING.ServiceReference1.USAPWebServiceSoap)(this)).GetDataPointConfirmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BIVN_PACKING.ServiceReference1.DailyResponse BIVN_PACKING.ServiceReference1.USAPWebServiceSoap.Daily(BIVN_PACKING.ServiceReference1.DailyRequest request) {
            return base.Channel.Daily(request);
        }
        
        public string Daily(System.DateTime input) {
            BIVN_PACKING.ServiceReference1.DailyRequest inValue = new BIVN_PACKING.ServiceReference1.DailyRequest();
            inValue.Body = new BIVN_PACKING.ServiceReference1.DailyRequestBody();
            inValue.Body.input = input;
            BIVN_PACKING.ServiceReference1.DailyResponse retVal = ((BIVN_PACKING.ServiceReference1.USAPWebServiceSoap)(this)).Daily(inValue);
            return retVal.Body.DailyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.DailyResponse> BIVN_PACKING.ServiceReference1.USAPWebServiceSoap.DailyAsync(BIVN_PACKING.ServiceReference1.DailyRequest request) {
            return base.Channel.DailyAsync(request);
        }
        
        public System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.DailyResponse> DailyAsync(System.DateTime input) {
            BIVN_PACKING.ServiceReference1.DailyRequest inValue = new BIVN_PACKING.ServiceReference1.DailyRequest();
            inValue.Body = new BIVN_PACKING.ServiceReference1.DailyRequestBody();
            inValue.Body.input = input;
            return ((BIVN_PACKING.ServiceReference1.USAPWebServiceSoap)(this)).DailyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BIVN_PACKING.ServiceReference1.MonthlyResponse BIVN_PACKING.ServiceReference1.USAPWebServiceSoap.Monthly(BIVN_PACKING.ServiceReference1.MonthlyRequest request) {
            return base.Channel.Monthly(request);
        }
        
        public string Monthly(System.DateTime input) {
            BIVN_PACKING.ServiceReference1.MonthlyRequest inValue = new BIVN_PACKING.ServiceReference1.MonthlyRequest();
            inValue.Body = new BIVN_PACKING.ServiceReference1.MonthlyRequestBody();
            inValue.Body.input = input;
            BIVN_PACKING.ServiceReference1.MonthlyResponse retVal = ((BIVN_PACKING.ServiceReference1.USAPWebServiceSoap)(this)).Monthly(inValue);
            return retVal.Body.MonthlyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.MonthlyResponse> BIVN_PACKING.ServiceReference1.USAPWebServiceSoap.MonthlyAsync(BIVN_PACKING.ServiceReference1.MonthlyRequest request) {
            return base.Channel.MonthlyAsync(request);
        }
        
        public System.Threading.Tasks.Task<BIVN_PACKING.ServiceReference1.MonthlyResponse> MonthlyAsync(System.DateTime input) {
            BIVN_PACKING.ServiceReference1.MonthlyRequest inValue = new BIVN_PACKING.ServiceReference1.MonthlyRequest();
            inValue.Body = new BIVN_PACKING.ServiceReference1.MonthlyRequestBody();
            inValue.Body.input = input;
            return ((BIVN_PACKING.ServiceReference1.USAPWebServiceSoap)(this)).MonthlyAsync(inValue);
        }
    }
}
